### ISSUE TITLE
ROOT interpreter built with C++17 does not find `std::optional` without including it first

### ISSUE THREAD

**Issue by kgizdov** [root-project/root#10221]
- [x] Checked for duplicates
### Describe the bug
`pyroot` installation with `c++17` does not find `optional` in namespace `std`:
```python
>>> import ROOT
>>> hasattr(ROOT.std, "optional")
False
```
### Expected behavior
```python
>>> import ROOT
>>> hasattr(ROOT.std, "optional")
True
```
### To Reproduce
1. Install `root`
2. run `python -c 'import ROOT; hasattr(ROOT.std, "optional")'`

### Setup
ROOT version: 6.26.00
OS: Arch Linux x86_64
GCC: 11.2.0
Python: 3.10.2
### Additional context
```bash
$ root-config --features
cxx17 asimage builtin_clang builtin_cling builtin_llvm ccache clad cuda cudnn dataframe exceptions fftw3 fitsio fortran gdml gnuinstall gsl_shared gviz http fcgi imt mathmore mlp minuit2 mpi mysql odbc opengl pgsql pyroot pythia8 qt5web roofit webgui root7 shadowpw shared sqlite ssl tmva tmva-gpu tmva-pymva spectrum unuran vc vdt x11 xml xrootd
```
```bash
$ root-config --config
CFITSIO_INCLUDE_DIR=/usr/include CFITSIO_LIBRARY=/usr/lib/libcfitsio.so CUDA_CUDART_LIBRARY=/opt/cuda/lib64/libcudart.so CUDA_CUDA_LIBRARY=/usr/lib/libcuda.so CUDA_OpenCL_LIBRARY=/opt/cuda/lib64/libOpenCL.so CUDA_TOOLKIT_INCLUDE=/opt/cuda/include CUDA_VERSION=11.6 CUDA_cublas_LIBRARY=/opt/cuda/lib64/libcublas.so CUDA_cudadevrt_LIBRARY=/opt/cuda/lib64/libcudadevrt.a CUDA_cudart_static_LIBRARY=/opt/cuda/lib64/libcudart_static.a CUDA_cufft_LIBRARY=/opt/cuda/lib64/libcufft.so CUDA_cupti_LIBRARY=/opt/cuda/extras/CUPTI/lib64/libcupti.so CUDA_curand_LIBRARY=/opt/cuda/lib64/libcurand.so CUDA_cusolver_LIBRARY=/opt/cuda/lib64/libcusolver.so CUDA_cusparse_LIBRARY=/opt/cuda/lib64/libcusparse.so CUDA_nppc_LIBRARY=/opt/cuda/lib64/libnppc.so CUDA_nppial_LIBRARY=/opt/cuda/lib64/libnppial.so CUDA_nppicc_LIBRARY=/opt/cuda/lib64/libnppicc.so CUDA_nppidei_LIBRARY=/opt/cuda/lib64/libnppidei.so CUDA_nppif_LIBRARY=/opt/cuda/lib64/libnppif.so CUDA_nppig_LIBRARY=/opt/cuda/lib64/libnppig.so CUDA_nppim_LIBRARY=/opt/cuda/lib64/libnppim.so CUDA_nppist_LIBRARY=/opt/cuda/lib64/libnppist.so CUDA_nppisu_LIBRARY=/opt/cuda/lib64/libnppisu.so CUDA_nppitc_LIBRARY=/opt/cuda/lib64/libnppitc.so CUDA_npps_LIBRARY=/opt/cuda/lib64/libnpps.so CUDA_nvToolsExt_LIBRARY=/opt/cuda/lib64/libnvToolsExt.so CUDA_rt_LIBRARY=/usr/lib/librt.a CUDNN_INCLUDE_DIR=/usr/include CUDNN_LIBRARY=/usr/lib/libcudnn.so CURL_INCLUDE_DIR=/usr/include CURL_LIBRARY_RELEASE=/usr/lib/libcurl.so FASTCGI_INCLUDE_DIR=/usr/include FASTCGI_LIBRARY=/usr/lib/libfcgi.so FFTW_INCLUDE_DIR=/usr/include FFTW_LIBRARY=/usr/lib/libfftw3.so FREETYPE_INCLUDE_DIR_freetype2=/usr/include/freetype2 FREETYPE_INCLUDE_DIR_ft2build=/usr/include/freetype2 FREETYPE_LIBRARY_RELEASE=/usr/lib/libfreetype.so FTGL_INCLUDE_DIR=/usr/include FTGL_LIBRARY=/lib/libftgl.so Fontconfig_INCLUDE_DIR=/usr/include Fontconfig_LIBRARY=/usr/lib/libfontconfig.so GIF_INCLUDE_DIR=/usr/include GIF_LIBRARY=/usr/lib/libgif.so GL2PS_INCLUDE_DIR=/usr/include GL2PS_LIBRARY=/lib/libgl2ps.so GLEW_INCLUDE_DIR=/usr/include GLEW_SHARED_LIBRARY_RELEASE=/usr/lib/libGLEW.so GRAPHVIZ_INCLUDE_DIR=/usr/include GRAPHVIZ_cdt_LIBRARY=/usr/lib/libcdt.so GRAPHVIZ_graph_LIBRARY=/usr/lib/libcgraph.so GRAPHVIZ_gvc_LIBRARY=/usr/lib/libgvc.so GRAPHVIZ_pathplan_LIBRARY=/usr/lib/libpathplan.so GSL_CBLAS_LIBRARY=/usr/lib/libgslcblas.so GSL_CBLAS_LIBRARY_DEBUG=/usr/lib/libgslcblas.so GSL_INCLUDEDIR=/usr/include GSL_INCLUDE_DIR=/usr/include GSL_INCLUDE_DIRS=/usr/include GSL_LIBRARY=/usr/lib/libgsl.so GSL_LIBRARY_DEBUG=/usr/lib/libgsl.so GSL_LIBRARY_DIRS=/usr/lib GSL_STATIC_LIBRARY_DIRS=/usr/lib GSL_VERSION=2.7.1 JPEG_INCLUDE_DIR=/usr/include JPEG_LIBRARY=/usr/lib/libjpeg.so JPEG_LIBRARY_RELEASE=/usr/lib/libjpeg.so LIBLZMA_INCLUDE_DIR=/usr/include LIBLZMA_LIBRARY=/usr/lib/liblzma.so LIBLZMA_LIBRARY_RELEASE=/usr/lib/liblzma.so LIBXML2_INCLUDE_DIR=/usr/include/libxml2 LIBXML2_LIBRARY=/usr/lib/libxml2.so LZ4_INCLUDE_DIR=/usr/include LZ4_LIBRARY=/usr/lib/liblz4.so MPI_mpi_LIBRARY=/usr/lib/openmpi/libmpi.so MPI_mpi_cxx_LIBRARY=/usr/lib/openmpi/libmpi_cxx.so MPI_mpi_mpifh_LIBRARY=/usr/lib/openmpi/libmpi_mpifh.so MPI_mpi_usempi_ignore_tkr_LIBRARY=/usr/lib/openmpi/libmpi_usempi_ignore_tkr.so MPI_mpi_usempif08_LIBRARY=/usr/lib/openmpi/libmpi_usempif08.so MYSQL_INCLUDE_DIR=/usr/include/mysql NUMPY_INCLUDE_DIRS=/usr/lib/python3.10/site-packages/numpy/core/include ODBC_INCLUDE_DIR=/usr/include ODBC_LIBRARY=/usr/lib/libodbc.so OPENGL_EGL_INCLUDE_DIR=/usr/include OPENGL_GLX_INCLUDE_DIR=/usr/include OPENGL_INCLUDE_DIR=/usr/include OPENGL_egl_LIBRARY=/usr/lib/libEGL.so OPENGL_glu_LIBRARY=/usr/lib/libGLU.so OPENGL_glx_LIBRARY=/usr/lib/libGLX.so OPENGL_opengl_LIBRARY=/usr/lib/libOpenGL.so OPENSSL_CRYPTO_LIBRARY=/usr/lib/libcrypto.so OPENSSL_INCLUDE_DIR=/usr/include OPENSSL_SSL_LIBRARY=/usr/lib/libssl.so PCRE_INCLUDE_DIR=/usr/include PCRE_PCRE_LIBRARY_DEBUG=/usr/lib/libpcre.so PCRE_PCRE_LIBRARY_RELEASE=/usr/lib/libpcre.so PC_CURL_INCLUDEDIR=/usr/include PC_CURL_LIBRARIES=curl PC_CURL_LIBRARY_DIRS=/usr/lib PC_CURL_STATIC_LIBRARY_DIRS=/usr/lib PC_CURL_VERSION=7.82.0 PC_LIBXML_INCLUDEDIR=/usr/include PC_LIBXML_INCLUDE_DIRS=/usr/include/libxml2 PC_LIBXML_LIBRARIES=xml2 PC_LIBXML_LIBRARY_DIRS=/usr/lib PC_LIBXML_STATIC_INCLUDE_DIRS=/usr/include/libxml2 PC_LIBXML_STATIC_LIBRARY_DIRS=/usr/lib PC_LIBXML_VERSION=2.9.13 PC_SQLITE_INCLUDEDIR=/usr/include PC_SQLITE_LIBRARIES=sqlite3 PC_SQLITE_LIBRARY_DIRS=/usr/lib PC_SQLITE_STATIC_LIBRARY_DIRS=/usr/lib PC_SQLITE_VERSION=3.38.0 PKG_FONTCONFIG_INCLUDEDIR=/usr/include PKG_FONTCONFIG_LIBRARY_DIRS=/usr/lib PKG_FONTCONFIG_VERSION=2.13.96 PNG_LIBRARY_RELEASE=/usr/lib/libpng.so PNG_PNG_INCLUDE_DIR=/usr/include PYTHIA8_INCLUDE_DIR=/usr/include PYTHIA8_LIBRARY=/usr/lib/libpythia8.so PYTHON_INCLUDE_DIRS=/usr/include/python3.10 PYTHON_LIBRARIES=/usr/lib/libpython3.10.so PYTHON_LIBRARY_DIR=/usr/lib PYTHON_VERSION_MAJOR=3 PYTHON_VERSION_MINOR=10 PYTHON_VERSION_STRING=3.10.2 PostgreSQL_INCLUDE_DIR=/usr/include PostgreSQL_LIBRARY=/usr/lib/libpq.so SQLITE_INCLUDE_DIR=/usr/include SQLITE_LIBRARIES=/usr/lib/libsqlite3.so TBB_INCLUDE_DIR=/usr/include TBB_LIBRARY=/usr/lib/libtbb.so TBB_LIBRARY_RELEASE=/usr/lib/libtbb.so TIFF_INCLUDE_DIR=/usr/include TIFF_LIBRARY_RELEASE=/usr/lib/libtiff.so UNURAN_INCLUDE_DIR=/usr/include UNURAN_LIBRARY=/lib/libunuran.so VDT_INCLUDE_DIR=/usr/include VDT_LIBRARY=/usr/lib/libvdt.so X11_ICE_INCLUDE_PATH=/usr/include X11_SM_INCLUDE_PATH=/usr/include X11_X11_INCLUDE_PATH=/usr/include X11_X11_xcb_INCLUDE_PATH=/usr/include X11_XShm_INCLUDE_PATH=/usr/include X11_XSync_INCLUDE_PATH=/usr/include X11_Xaccessrules_INCLUDE_PATH=/usr/includeX11_Xaccessstr_INCLUDE_PATH=/usr/include X11_Xau_INCLUDE_PATH=/usr/include X11_Xcomposite_INCLUDE_PATH=/usr/include X11_Xcursor_INCLUDE_PATH=/usr/include X11_Xdamage_INCLUDE_PATH=/usr/include X11_Xdmcp_INCLUDE_PATH=/usr/include X11_Xext_INCLUDE_PATH=/usr/include X11_Xfixes_INCLUDE_PATH=/usr/include X11_Xft_INCLUDE_PATH=/usr/include X11_Xi_INCLUDE_PATH=/usr/include X11_Xinerama_INCLUDE_PATH=/usr/include X11_Xkb_INCLUDE_PATH=/usr/include X11_Xkblib_INCLUDE_PATH=/usr/include X11_Xlib_INCLUDE_PATH=/usr/include X11_Xmu_INCLUDE_PATH=/usr/include X11_Xpm_INCLUDE_PATH=/usr/include X11_Xrandr_INCLUDE_PATH=/usr/include X11_Xrender_INCLUDE_PATH=/usr/include X11_Xshape_INCLUDE_PATH=/usr/include X11_Xss_INCLUDE_PATH=/usr/include X11_Xt_INCLUDE_PATH=/usr/include X11_Xtst_INCLUDE_PATH=/usr/include X11_Xutil_INCLUDE_PATH=/usr/include X11_Xv_INCLUDE_PATH=/usr/include X11_Xxf86vm_INCLUDE_PATH=/usr/include X11_dpms_INCLUDE_PATH=/usr/include X11_xcb_INCLUDE_PATH=/usr/include X11_xcb_icccm_INCLUDE_PATH=/usr/include X11_xcb_util_INCLUDE_PATH=/usr/include X11_xcb_xfixes_INCLUDE_PATH=/usr/include X11_xkbcommon_INCLUDE_PATH=/usr/include X11_xkbcommon_X11_INCLUDE_PATH=/usr/include X11_xkbfile_INCLUDE_PATH=/usr/include XROOTD_INCLUDE_DIR=/usr/include/xrootd XROOTD_XrdCl_LIBRARY=/usr/lib/libXrdCl.so XROOTD_XrdUtils_LIBRARY=/usr/lib/libXrdUtils.so ZLIB_INCLUDE_DIR=/usr/include ZLIB_LIBRARY_RELEASE=/usr/lib/libz.so ZSTD_INCLUDE_DIR=/usr/include ZSTD_LIBRARIES=/usr/lib/libzstd.so xxHash_INCLUDE_DIR=/usr/include xxHash_LIBRARY=/usr/lib/libxxhash.so
```

**Comment by etejedor** [comment]
Tried on one of our nightly C++17 nightly builds (gcc9.4, python3.8, ubuntu2004) and I can't reproduce.

Can you check if `std::optional` can be used at the ROOT prompt from C++?

**Comment by guitargeek** [comment]
Hi @kgizdov, thanks for reporting this!

I can reproduce the problem, building ROOT master on ArchLinux with C++17, with the same settings as used for the actual package:
https://gitlab.archlinux.org/archlinux/packaging/packages/root/-/blob/main/settings.cmake?ref_type=heads

However, the problem can easily be worked around by including `<optional>` after importing ROOT:

```c++
import ROOT
ROOT.gInterpreter.ProcessLine("#include <optional>")
ROOT.std.optional
```

The same is necessary in the C++ prompt, so this is actually not a PyROOT problem but starts with the interpreter.

Also, when building with C++20, the problem is gone!

So given that there is an easy workaround for C++17 builds and the problem will be gone once everyone will be using C++20, I don't think we need to prioritize this issue, and maybe just close it at some point.

@kgizdov, any thoughts on that?

**Comment by dpiparo** [comment]
Since I cannot reproduce any more on macos nor linux, I am closing the issue. Please feel free to re-open in case this is still a problem and we have overlooked something.
