### ISSUE TITLE
[tmva] Wrong result when evaluating a TMVA CNN a GPU trained model with BNORM layer on CPU 

### ISSUE THREAD

**Issue by lmoneta** [root-project/root#12589]
As reported in https://root-forum.cern.ch/t/tmva-read-image-data-for-application-of-a-cnn-model/54181/15 
and shown in this notebook example
https://cernbox.cern.ch/s/U7p6sgH7QN4GRlX

A CNN model that is trained on GPU and containing a BNORM layer produces wring results (all 0 or 1) when is evaluated (e.g. using RReader) on CPU. 
The evaluation that is done in the Classification macro (in `Factory::EvcaluateAllMethods`) is performed on GPU. 
This happens only when the model contains the BNORM layer.

**Comment by ferdymercury** [comment]
@lmoneta is this still the case or was this solved in the meanwhile?

**Comment by lmoneta** [comment]
I don't know, it would need to be tested using a GPU node. It is possible that using new versions of cuDNN this problem is gone
